---

- hosts: localhost
  tasks:
    - name: Parse demo parameters and context
      no_log: True # To not log sensitive information
      set_fact:
        # Unpack the base64 encoded JSON string into a dictionary
        context: "{{ lookup('env', 'DEMO_CONTEXT_BASE64') | b64decode | from_json }}"

        # Use the token for the hosting organization of the demo repository
        github_token: "{{ lookup('env', 'OD_OCTODEMO_DEMO_APP_TOKEN') }}"

    - name: Validate Context
      assert:
        that:
          - context is defined

          - context.demo_instance_context is defined
          - context.demo_instance_context.demo_instance_name is defined
          - context.demo_instance_context.demo_org is defined
          - context.demo_instance_context.demo_org.owner is defined
          - context.demo_instance_context.demo_org.github_api_url is defined

          - github_token is defined

    - name: Set repository API URL
      set_fact:
        repository_api_url: "{{ context.demo_instance_context.demo_org.github_api_url }}/repos/{{ context.demo_instance_context.demo_org.owner }}/{{ context.demo_instance_context.demo_instance_name }}"

    - name: Create GitHub issue
      uri:
        url: "{{ repository_api_url }}/issues"
        method: POST
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_token }}
          Content-Type: "application/json"
        body_format: json
        body:
          title: "Sample title {{ context.demo_instance_context.demo_instance_name }}"
          body: |
            ## 🎉 Sample body
          labels:
            - "invalid"
          assignees:
            - "viniciusvmda"
        status_code: 201
      register: issue_creation_result
      retries: 3
      delay: 5
      until: issue_creation_result.status == 201

    - name: Display created issue information
      debug:
        msg: |
          Successfully created GitHub issue:
          - Issue Number: {{ issue_creation_result.json.number }}
          - Issue URL: {{ issue_creation_result.json.html_url }}
          - Title: {{ issue_creation_result.json.title }}
