---

- hosts: localhost
  tasks:
    - name: Parse demo parameters and context
      no_log: True # To not log sensitive information
      set_fact:
        # Unpack the base64 encoded JSON string into a dictionary
        context: "{{ lookup('env', 'DEMO_CONTEXT_BASE64') | b64decode | from_json }}"

        # Use the token for the hosting organization of the demo repository
        github_token: "{{ lookup('env', 'OD_OCTODEMO_DEMO_APP_TOKEN') }}"

    - name: Validate Context
      assert:
        that:
          - context is defined

          - context.demo_instance_context is defined
          - context.demo_instance_context.demo_instance_name is defined
          - context.demo_instance_context.demo_org is defined
          - context.demo_instance_context.demo_org.owner is defined
          - context.demo_instance_context.demo_org.github_api_url is defined

          - github_token is defined

    - name: Set repository API URL
      set_fact:
        repository_api_url: "{{ context.demo_instance_context.demo_org.github_api_url }}/repos/{{ context.demo_instance_context.demo_org.owner }}/{{ context.demo_instance_context.demo_instance_name }}"

    - name: Load issue content from JSON file
      set_fact:
        body: "{{ lookup('file', 'unittest-issue-' + context.demo_instance_context.demo_options.backend + '.md') }}"

    - name: Create GitHub issue
      uri:
        url: "{{ repository_api_url }}/issues"
        method: POST
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_token }}
          Content-Type: "application/json"
        body_format: json
        body:
          title: "Improve test coverage for API"
          body: "{{ body }}"
          labels:
            - "demo"
            - "quality"  
        status_code: 201
      register: issue_creation_result
      retries: 3
      delay: 5
      until: issue_creation_result.status == 201

    - name: Display created issue information
      debug:
        msg: |
          Successfully created GitHub issue:
          - Issue Number: {{ issue_creation_result.json.number }}
          - Issue URL: {{ issue_creation_result.json.html_url }}
          - Title: {{ issue_creation_result.json.title }}
    
    - name: Get list of all branches
      uri:
        url: "{{ repository_api_url }}/branches"
        method: GET
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_token }}
        status_code: 200
      register: branches_result
      retries: 3
      delay: 5
      until: branches_result.status == 200
      
    - name: Set default branch to backend branch
      uri:
        url: "{{ repository_api_url }}"
        method: PATCH
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_token }}
        body_format: json
        body:
          default_branch: "{{ context.demo_instance_context.demo_options.backend }}"
        status_code: 200
      register: set_default_branch_result
      retries: 3
      delay: 5
      until: set_default_branch_result.status == 200
      when: context.demo_instance_context.demo_options.backend != "nodejs"

    - name: Delete branches other than the backend branch
      uri:
        url: "{{ repository_api_url }}/git/refs/heads/{{ item.name }}"
        method: DELETE
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_token }}
        status_code: [204, 422]  # 422 for protected branches that can't be deleted
      register: delete_branch_result
      retries: 3
      delay: 5
      until: delete_branch_result.status in [204, 422]
      loop: "{{ branches_result.json }}"
      when: item.name != context.demo_instance_context.demo_options.backend

    - name: Rename the branch to main
      uri:
        url: "{{ repository_api_url }}/branches/{{ context.demo_instance_context.demo_options.backend }}/rename"
        method: POST
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: bearer {{ github_token }}
        body_format: json
        body:
          new_name: "main"
        status_code: 201
      register: rename_branch_result
      retries: 3
      delay: 5
      until: rename_branch_result.status == 201
